# Generated by Django 6.0.3 on 2026-03-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='description',
            field=models.CharField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
